name: Master - Build Latest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm and dependencies
        run: npm install -g npm@latest && npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

      - uses: azure/docker-login@v1
        with:
          login-server: growthcloud.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -f docker/images/n8n-custom/Dockerfile -t growthcloud.azurecr.io/gcautomation:latest
          docker push growthcloud.azurecr.io/gcautomation:latest
